PartyInvites/Models/GuestResponse.cs
using System.ComponentModel.DataAnnotations;

namespace PartyInvites.Models
{
    public class GuestResponse
    {
        [Required]
        public string Nama { get; set; }

        [Required]
        public string Alamat { get; set; }

        [Required]
        public string Umur { get; set; }
    }
}

PartyInvites/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PartyInvites.Models
{
    public class Repository
    {
        private static Dictionary<string, GuestResponse> responses;
        static Repository()
        {
            responses = new Dictionary<string, GuestResponse>();
            responses.Add("Ucu", new GuestResponse
            {
                Nama = "Ucu",
                Alamat = "Serang",
                Umur = "27"
            });
            responses.Add("Trio", new GuestResponse
            {
                Nama = "Trio",
                Alamat = "Bogor Utara",
                Umur = "22"
            });
           
        }
        public static void Add(GuestResponse newResponse)
        {
            string key = newResponse.Nama.ToLowerInvariant();
            if (responses.ContainsKey(key))
            {
                responses[key] = newResponse;
            }
            else {
                responses.Add(key, newResponse);
            }
        }
        public static IEnumerable<GuestResponse> Responses
        {
            get { return responses.Values; }
        }
    }
}

PartyInvites/Controllers/HomeController.cs
using System.Web.Mvc;
using PartyInvites.Models;
using System.Linq;

namespace PartyInvites.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Rsvp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Rsvp(GuestResponse response)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(response);
                return View("Thanks", response);
            }
            else {
                return View();
            }
        }
        [ChildActionOnly]
        public ActionResult Attendees()
        {
            return View();
        }
    }
}

PartyInvites/Controllers/RsvpController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using PartyInvites.Models;
namespace PartyInvites.Controllers
{
    public class RsvpController : ApiController
    {
        public IEnumerable<GuestResponse> GetAttendees()
        {
            return Repository.Responses;
        }

        public void PostResponse(GuestResponse response)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(response);
            }
        }
    }
}

PartyInvites/Views/Home/Attendees.cshtml
    <p>
        Data Anda bisa dilihat pada api
    </p>

PartyInvites/Views/Home/Index.cshtml
@{ ViewBag.Title = "Selamat datang!";}
<div class="text-center">
    <h2>Silahkan tekan tombol berikut untuk post data!</h2>
    
    @Html.ActionLink("Lanjutkan", "Rsvp", null, new { @class = "btn btn-success" })
</div>

PartyInvites/Views/Home/Rsvp.cshtml
@model PartyInvites.Models.GuestResponse
@{ ViewBag.Title = "Rsvp"; }
<div class="panel panel-success">
    <div class="panel-heading"><h4>RSVP</h4></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>Nama:</label>
                @Html.TextBoxFor(x => x.Nama, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Alamat:</label>
                @Html.TextBoxFor(x => x.Alamat, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Umur:</label>
                @Html.TextBoxFor(x => x.Umur, new { @class = "form-control" })
            </div>
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Kirim Data" />
            </div>
        }
    </div>
</div>

PartyInvites/Views/Home/Thanks.cshtml
@model PartyInvites.Models.GuestResponse
@{ ViewBag.Title = "Thanks";}
<h1>Thank you, @Model.Nama!</h1>
<div class="lead">
    
       Selamat! Data Anda telah tersimpan!

        @Html.Action("Attendees", "Home")
    
</div>

PartyInvites/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-2.1.0.min.js"></script>
    <script src="~/Scripts/knockout-3.1.0.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/rsvp.js"></script>
    <style>
        body {
            padding-top: 10px;
        }
    </style>
</head>
<body class="container">
    @RenderBody()
</body>
</html>